api:
  dashboard: false
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secureweb
          scheme: https
          permanent: false

  secureweb:
    address: ":443"

  dashboard:
    address: ":8080"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: newspace@gamil.com
      storage: /traefik/acme.json
      httpChallenge:
        entryPoint: secureweb

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /traefik/dashboard.yaml
    watch: true